# Theme metadata.
name = "Theme Name"
author = "Garry Pettet"
version = "1.0.0"

# Generic tokens.
backColor = "&h00FFFFFF"
textColor = "&h00000000"
textSelectionColor = "&h00A4CCFE"

# Block folding.
blockFoldedColor = "&h00FF8000"
blockFoldedEllipsisColor = "&h00AAAAAA"
blockFoldMarkerColor = "&h00555555"

# Left gutter colours.
gutterBackColor = "&h00FFFFFF"
gutterBorderColor = "&h00000000"
lineNumbersColor = "&h00000000"

# Autocomplete colours.
suggestionPopupBackColor = "&h00FFFFFF"
suggestionPopupSelectedTextColor = "&h00000000"
suggestionPopupTextColor = "&h00000000"

# Miscellaneous.
bookmarkColor = "&h000000FF"
bracketHighlightColor = "&h000000FF"
caretColor = "&h00000000"
dirtyLinesColor = "&h00FFFF00"
invisibleCharacterColor = "&h00BFC5CC"
verticalRulerColor = "&h00AAAAAA"

# The required default style. Used for text that matches no other style.
[defaultStyle]
textColor = "&h00000000"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

# ==============================================
# Required styles. All themes must define these.
# ==============================================
[styles.comment]
textColor = "&h00737373"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = true
underline = false

[styles.directive]
textColor = "&h007C3EA6"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.escape]
textColor = "&h0000ff00"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.identifier]
textColor = "&h00B42F84"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.keyword]
textColor = "&h000061B8"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.lowercaseIdentifier]
textColor = "&h00B42F84"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.number]
textColor = "&h00000000"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.placeholder]
textColor = "&h00FFFFFF"
backColor = "&h003379F7"
hasBackColor = false
bold = true
italic = false
underline = false

[styles.string]
textColor = "&h00BD391D"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.type]
textColor = "&h00000000"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.uppercaseIdentifier]
textColor = "&h0023575A"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = false

[styles.url]
textColor = "&h00000000"
backColor = "&h00000000"
hasBackColor = false
bold = false
italic = false
underline = true
